coverage:
  precision: 2
  round: nearest
  range: "80...100"
  status:
    project:
      sockify:
        threshold: 2%

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - name: Core Library
      component_id: core-lib
      paths:
        - src/sockify/lib/**
        - src/sockify/include/**
    - name: Command Line Interface
      component_id: cli
      paths:
        - src/sockify/cli/**

ignore:
  - ^(?!src).*

comment:
  layout: "header, diff, components"
  behavior: once
