# This workflow builds and tests the project on multiple platforms (Ubuntu, macOS, Windows).
# It consists of two jobs: `build` to compile the project and upload build artifacts, and `test` to download
# the artifacts and run the tests. On Linux and macOS, the workflow also generates a code coverage report
# using `gcov -pb` and uploads it to Codecov.
#
# Build artifacts are uploaded only if the build succeeds, and the test job runs only after a successful build.

name: build and test project (multi)
on: [push, pull_request]

permissions:
  contents: read # Default everything to read-only

concurrency:
  # The concurrency group contains the workflow name and the branch name for
  # pull requests or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup cmake and build
        id: cmake_build
        uses: threeal/cmake-action@v2
        with:
          source-dir: .
          build-dir: ${{ matrix.os }}-${{ runner.arch }}
          run-build: true
          options: |
            SOCKIFY_DEVELOPMENT_BUILD=ON
            SOCKIFY_BUILD_DOCS=OFF

      - name: Upload build artifacts
        uses: pyTooling/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ runner.arch }}
          path: ${{ steps.cmake_build.outputs.build-dir }}
          if-no-files-found: error
          include-hidden-files: true

  test:
    runs-on: ${{ matrix.os }}
    needs: [ build ]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: pyTooling/download-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ runner.arch }}

      - name: Set up test environment variables
        run: |
          echo "BUILD_DIR=${{ matrix.os }}-${{ runner.arch }}" >> "$GITHUB_ENV"
          echo "TEST_DIR=${{ matrix.os }}-${{ runner.arch }}${{ matrix.os == 'windows-latest' && '\\tests' || '/tests' }}" >> "$GITHUB_ENV"

      - name: Run tests
        timeout-minutes: 25
        working-directory: ${{ env.TEST_DIR }}
        run: |
          ctest --output-on-failure

      - name: Generate coverage with gcov
        if: ${{ !cancelled() && (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest') }}
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          find . -type f -name '*.gcno' -exec gcov -pb {} + || true

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() && (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest') }}
        timeout-minutes: 20
        uses: codecov/codecov-action@v5
        with:
          name: codecov-${{ matrix.os }}
          directory: ${{ env.BUILD_DIR }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() && (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest') }}
        uses: codecov/test-results-action@v1
        with:
          files: ${{ env.TEST_DIR }}/sockify-test-results.xml
          token: ${{ secrets.CODECOV_TOKEN }}
